/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutAboutImport } from './routes/_layout/about'
import { Route as LayoutPlayersIndexImport } from './routes/_layout/players/index'
import { Route as LayoutGamesIndexImport } from './routes/_layout/games/index'
import { Route as LayoutCorporationsIndexImport } from './routes/_layout/corporations/index'
import { Route as LayoutToolsMapImport } from './routes/_layout/tools/map'
import { Route as LayoutToolsEloSimulatorImport } from './routes/_layout/tools/elo-simulator'
import { Route as LayoutPlayersPlayerIdImport } from './routes/_layout/players/$playerId'
import { Route as LayoutGamesGameIdImport } from './routes/_layout/games/$gameId'
import { Route as LayoutCorporationsCorporationIdImport } from './routes/_layout/corporations/$corporationId'
import { Route as LayoutAuthenticatedToolsSubmitImport } from './routes/_layout/_authenticated/tools/submit'

// Create/Update Routes

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAboutRoute = LayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPlayersIndexRoute = LayoutPlayersIndexImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGamesIndexRoute = LayoutGamesIndexImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCorporationsIndexRoute = LayoutCorporationsIndexImport.update({
  id: '/corporations/',
  path: '/corporations/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutToolsMapRoute = LayoutToolsMapImport.update({
  id: '/tools/map',
  path: '/tools/map',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutToolsEloSimulatorRoute = LayoutToolsEloSimulatorImport.update({
  id: '/tools/elo-simulator',
  path: '/tools/elo-simulator',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPlayersPlayerIdRoute = LayoutPlayersPlayerIdImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGamesGameIdRoute = LayoutGamesGameIdImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCorporationsCorporationIdRoute =
  LayoutCorporationsCorporationIdImport.update({
    id: '/corporations/$corporationId',
    path: '/corporations/$corporationId',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAuthenticatedToolsSubmitRoute =
  LayoutAuthenticatedToolsSubmitImport.update({
    id: '/_authenticated/tools/submit',
    path: '/tools/submit',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/corporations/$corporationId': {
      id: '/_layout/corporations/$corporationId'
      path: '/corporations/$corporationId'
      fullPath: '/corporations/$corporationId'
      preLoaderRoute: typeof LayoutCorporationsCorporationIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/games/$gameId': {
      id: '/_layout/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof LayoutGamesGameIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/players/$playerId': {
      id: '/_layout/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof LayoutPlayersPlayerIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/tools/elo-simulator': {
      id: '/_layout/tools/elo-simulator'
      path: '/tools/elo-simulator'
      fullPath: '/tools/elo-simulator'
      preLoaderRoute: typeof LayoutToolsEloSimulatorImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/tools/map': {
      id: '/_layout/tools/map'
      path: '/tools/map'
      fullPath: '/tools/map'
      preLoaderRoute: typeof LayoutToolsMapImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/corporations/': {
      id: '/_layout/corporations/'
      path: '/corporations'
      fullPath: '/corporations'
      preLoaderRoute: typeof LayoutCorporationsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/games/': {
      id: '/_layout/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof LayoutGamesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/players/': {
      id: '/_layout/players/'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof LayoutPlayersIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_authenticated/tools/submit': {
      id: '/_layout/_authenticated/tools/submit'
      path: '/tools/submit'
      fullPath: '/tools/submit'
      preLoaderRoute: typeof LayoutAuthenticatedToolsSubmitImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCorporationsCorporationIdRoute: typeof LayoutCorporationsCorporationIdRoute
  LayoutGamesGameIdRoute: typeof LayoutGamesGameIdRoute
  LayoutPlayersPlayerIdRoute: typeof LayoutPlayersPlayerIdRoute
  LayoutToolsEloSimulatorRoute: typeof LayoutToolsEloSimulatorRoute
  LayoutToolsMapRoute: typeof LayoutToolsMapRoute
  LayoutCorporationsIndexRoute: typeof LayoutCorporationsIndexRoute
  LayoutGamesIndexRoute: typeof LayoutGamesIndexRoute
  LayoutPlayersIndexRoute: typeof LayoutPlayersIndexRoute
  LayoutAuthenticatedToolsSubmitRoute: typeof LayoutAuthenticatedToolsSubmitRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCorporationsCorporationIdRoute: LayoutCorporationsCorporationIdRoute,
  LayoutGamesGameIdRoute: LayoutGamesGameIdRoute,
  LayoutPlayersPlayerIdRoute: LayoutPlayersPlayerIdRoute,
  LayoutToolsEloSimulatorRoute: LayoutToolsEloSimulatorRoute,
  LayoutToolsMapRoute: LayoutToolsMapRoute,
  LayoutCorporationsIndexRoute: LayoutCorporationsIndexRoute,
  LayoutGamesIndexRoute: LayoutGamesIndexRoute,
  LayoutPlayersIndexRoute: LayoutPlayersIndexRoute,
  LayoutAuthenticatedToolsSubmitRoute: LayoutAuthenticatedToolsSubmitRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/about': typeof LayoutAboutRoute
  '/': typeof LayoutIndexRoute
  '/corporations/$corporationId': typeof LayoutCorporationsCorporationIdRoute
  '/games/$gameId': typeof LayoutGamesGameIdRoute
  '/players/$playerId': typeof LayoutPlayersPlayerIdRoute
  '/tools/elo-simulator': typeof LayoutToolsEloSimulatorRoute
  '/tools/map': typeof LayoutToolsMapRoute
  '/corporations': typeof LayoutCorporationsIndexRoute
  '/games': typeof LayoutGamesIndexRoute
  '/players': typeof LayoutPlayersIndexRoute
  '/tools/submit': typeof LayoutAuthenticatedToolsSubmitRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/about': typeof LayoutAboutRoute
  '/': typeof LayoutIndexRoute
  '/corporations/$corporationId': typeof LayoutCorporationsCorporationIdRoute
  '/games/$gameId': typeof LayoutGamesGameIdRoute
  '/players/$playerId': typeof LayoutPlayersPlayerIdRoute
  '/tools/elo-simulator': typeof LayoutToolsEloSimulatorRoute
  '/tools/map': typeof LayoutToolsMapRoute
  '/corporations': typeof LayoutCorporationsIndexRoute
  '/games': typeof LayoutGamesIndexRoute
  '/players': typeof LayoutPlayersIndexRoute
  '/tools/submit': typeof LayoutAuthenticatedToolsSubmitRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/corporations/$corporationId': typeof LayoutCorporationsCorporationIdRoute
  '/_layout/games/$gameId': typeof LayoutGamesGameIdRoute
  '/_layout/players/$playerId': typeof LayoutPlayersPlayerIdRoute
  '/_layout/tools/elo-simulator': typeof LayoutToolsEloSimulatorRoute
  '/_layout/tools/map': typeof LayoutToolsMapRoute
  '/_layout/corporations/': typeof LayoutCorporationsIndexRoute
  '/_layout/games/': typeof LayoutGamesIndexRoute
  '/_layout/players/': typeof LayoutPlayersIndexRoute
  '/_layout/_authenticated/tools/submit': typeof LayoutAuthenticatedToolsSubmitRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/logout'
    | '/about'
    | '/'
    | '/corporations/$corporationId'
    | '/games/$gameId'
    | '/players/$playerId'
    | '/tools/elo-simulator'
    | '/tools/map'
    | '/corporations'
    | '/games'
    | '/players'
    | '/tools/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/logout'
    | '/about'
    | '/'
    | '/corporations/$corporationId'
    | '/games/$gameId'
    | '/players/$playerId'
    | '/tools/elo-simulator'
    | '/tools/map'
    | '/corporations'
    | '/games'
    | '/players'
    | '/tools/submit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_layout'
    | '/login'
    | '/logout'
    | '/_layout/about'
    | '/_layout/'
    | '/_layout/corporations/$corporationId'
    | '/_layout/games/$gameId'
    | '/_layout/players/$playerId'
    | '/_layout/tools/elo-simulator'
    | '/_layout/tools/map'
    | '/_layout/corporations/'
    | '/_layout/games/'
    | '/_layout/players/'
    | '/_layout/_authenticated/tools/submit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/_layout",
        "/login",
        "/logout"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/about",
        "/_layout/",
        "/_layout/corporations/$corporationId",
        "/_layout/games/$gameId",
        "/_layout/players/$playerId",
        "/_layout/tools/elo-simulator",
        "/_layout/tools/map",
        "/_layout/corporations/",
        "/_layout/games/",
        "/_layout/players/",
        "/_layout/_authenticated/tools/submit"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/_layout/about": {
      "filePath": "_layout/about.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/corporations/$corporationId": {
      "filePath": "_layout/corporations/$corporationId.tsx",
      "parent": "/_layout"
    },
    "/_layout/games/$gameId": {
      "filePath": "_layout/games/$gameId.tsx",
      "parent": "/_layout"
    },
    "/_layout/players/$playerId": {
      "filePath": "_layout/players/$playerId.tsx",
      "parent": "/_layout"
    },
    "/_layout/tools/elo-simulator": {
      "filePath": "_layout/tools/elo-simulator.tsx",
      "parent": "/_layout"
    },
    "/_layout/tools/map": {
      "filePath": "_layout/tools/map.tsx",
      "parent": "/_layout"
    },
    "/_layout/corporations/": {
      "filePath": "_layout/corporations/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/games/": {
      "filePath": "_layout/games/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/players/": {
      "filePath": "_layout/players/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/_authenticated/tools/submit": {
      "filePath": "_layout/_authenticated/tools/submit.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
